### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by joeflynn** [farinspace/wpalchemy#101]
There hasn't been much activity on this project in months, and there are multiple outstanding issues and pull requests. I understand priorities change and I'm not entitled to updates for something I'm not paying for. I'm just curious if I need to create & maintain my own fork if I need to contribute something.

Thanks!

**Comment by farinspace** [comment]
Joe, I've simply been away from it for too long. Contributions/maintainer welcome!

**Comment by farinspace** [comment]
organizing, clearing old issues .. will maintain and make fixes to a 1.x branch for now
