### ISSUE TITLE
Error with PHP7

### ISSUE THREAD

**Issue by generatepress** [farinspace/wpalchemy#102]
Was testing with PHP7 and found the following:

    PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; WPAlchemy_MetaBox has a deprecated constructor in /wpalchemy/MetaBox.php on line 55

Might be worth tweaking.

**Comment by helgatheviking** [comment]
Pretty sure this can be fixed by changing 

`function WPAlchemy_MetaBox($arr)`

to

`function __construct($arr)`

[here](https://github.com/farinspace/wpalchemy/blob/master/wp-content/wpalchemy/MetaBox.php#L448)

**Comment by generatepress** [comment]
Awesome - this works!
