### ISSUE TITLE
Custom Metabox Image Upload Button Not Saving URL

### ISSUE THREAD

**Issue by astewes** [farinspace/wpalchemy#103]
I'm using WPAlchemy's repeating field spec, which contains an image upload button. I've followed the WPAlchemy [walkthrough](https://www.youtube.com/watch?v=4DU-jX0j96g) to a T, but when I upload an image and click "Insert Into Post" the image URL isn't saved in the metabox input field.

**Here's how I'm setting up the metabox functionality in functions.php:**

    // MetaBox.php is version 1.5.2
    include_once WP_CONTENT_DIR . '/wpalchemy/MetaBox.php';
    // MediaAccess.php is version 0.2.1
    include_once WP_CONTENT_DIR . '/wpalchemy/MediaAccess.php';

    if (is_admin()) add_action('admin_enqueue_scripts', 'metabox_style');

    function metabox_style() {
      wp_enqueue_style('wpalchemy-metabox', get_stylesheet_directory_uri() . '/metaboxes/meta.css');
    }

    $wpalchemy_media_access = new WPAlchemy_MediaAccess();

    $custom_mb = new WPAlchemy_MetaBox(array
    (
      'id' => 'custom_meta',
      'title' => 'My Custom Meta',
      'template' => get_stylesheet_directory() . '/metaboxes/repeating_fields_meta.php',
      'types' => array('meetups')
    ));

**Here's what I have in repeating_fields_meta.php:**

    <?php global $wpalchemy_media_access; ?>
    <div class="my_meta_control">

        <p><a href="#" class="dodelete-docs button">Remove All</a></p>

        <?php while($metabox->have_fields_and_multi('docs')): ?>
        <?php $metabox->the_group_open(); ?>

            <a href="#" class="dodelete button">Remove</a>

            <?php $metabox->the_field('imgurl'); ?>
            <?php $wpalchemy_media_access->setGroupName( 'img-n' . $metabox->get_the_index() )->setInsertButtonLabel('Insert'); ?>

            <p>
                <?php echo $wpalchemy_media_access->getField( array( 'name' => $metabox->get_the_name(), 'value' => $metabox->get_the_value() ) ); ?>
                <?php echo $wpalchemy_media_access->getButton(); ?>
            </p>

            <?php $metabox->the_field('title'); ?>
            <label for="<?php $metabox->the_name(); ?>">Title</label>
            <p><input type="text" id="<?php $metabox->the_name(); ?>" name="<?php $metabox->the_name(); ?>" value="<?php $metabox->the_value(); ?>"/></p>

        <?php $metabox->the_group_close(); ?>
        <?php endwhile; ?>

        <p style="margin-bottom:15px; padding-top:5px;"><a href="#" class="docopy-docs button">Add</a></p>
    </div>

**And here's how I'm defining my "meetups" custom post type in functions.php:**

    add_action('init', 'create_meetups_post_type');

    function create_meetups_post_type() {
      $meetup_labels = array(
        'name' => 'Meetups',
        'singular_name' => 'Meetup',
        'add_new' => 'Add Meetup',
        'add_new_item' => 'Add Meetup',
        'edit' => 'Edit Meetup',
        'edit_item' => 'Edit Meetup',
        'new_item' => 'New Meetup',
        'view' => 'View Meetup',
        'view_item' => 'View Meetup',
        'search_items' => 'Search Meetup',
        'not_found' => 'No meetups Found',
        'not_found_in_trash' => 'No meetups found in trash'
      );
      $args = array(
        'labels' => $meetup_labels,
        'description' => 'Meetups custom post type',
        'public' => true,
        'publicly_queryable' => true,
        'show_ui' => true,
        'query_var' => true,
        'rewrite' => array('slug' => 'meetups', 'with_front' => false),
        'capability_type' => 'post',
        'menu_position' => 4,
        'taxonomies' => array('post_tag'),
        'exclude_from_search' => false,
        'supports' => array('title', 'revisions', 'thumbnail', 'page-attributes'),
        'menu_icon' => 'dashicons-groups',
      );
      register_post_type('meetups', $args);
    }

Given how closely I've followed the above-linked walkthrough, I can't figure out why the image URL isn't being saved and inserted into the metabox input. Am I missing something here?

**Comment by farinspace** [comment]
The MediaAccess class was really experimental .. I would recommend doing your own integration with the media uploader .. here is a article which might help with that.

http://www.sitepoint.com/adding-a-media-button-to-the-content-editor/

I will review and update the class if it makes sense.

**Comment by astewes** [comment]
Thanks for sending. After reviewing the article, I think there may be too many question marks involved. The article explains how to add a media button by hooking into the media_buttons action, but the process is going to be a lot different if I'm wanting to integrate this into the WPAlchemy repeating field metaboxes (that is, of course, you were implying I should scrap using MediaAccess.php altogether).

I'm also still wondering why, after mirroring your example, I was unable to get the uploader working? Unless it's a WP version or plugin issue, that doesn't make sense to me.

**Comment by farinspace** [comment]
Yeah, its the version of the WP .. MediaAccess was experimental and WordPress Media Upload APIs have changed.

Here is the implementation, give it a go:

**repeating_fields_meta.php**
```
<?php global $wpalchemy_media_access; ?>
<div class="my_meta_control">

    <p><a href="#" class="dodelete-docs button">Remove All</a></p>

    <?php while($metabox->have_fields_and_multi('docs')): ?>
    <?php $metabox->the_group_open(); ?>

        <a href="#" class="dodelete button">Remove</a>

        <?php $metabox->the_field('imgurl'); ?>
        <label for="<?php $metabox->the_name(); ?>">Image</label>
        <p><input type="text" id="<?php $metabox->the_name(); ?>" name="<?php $metabox->the_name(); ?>" value="<?php $metabox->the_value(); ?>"/>
        <button data-dest-selector="#<?php $metabox->the_name(); ?>" class="button">Add Media</button></p>

        <?php $metabox->the_field('title'); ?>
        <label for="<?php $metabox->the_name(); ?>">Title</label>
        <p><input type="text" id="<?php $metabox->the_name(); ?>" name="<?php $metabox->the_name(); ?>" value="<?php $metabox->the_value(); ?>"/></p>

    <?php $metabox->the_group_close(); ?>
    <?php endwhile; ?>

    <p style="margin-bottom:15px; padding-top:5px;"><a href="#" class="docopy-docs button">Add</a></p>
</div>
<script>
	jQuery(function($){
		var dest_selector;
		var media_window = wp.media({
	        title: 'Add Media',
	        library: {type: 'image'},
	        multiple: false,
	        button: {text: 'Add'}
	    });
	    media_window.on('select', function() {
	        var first = media_window.state().get('selection').first().toJSON();
	        $(dest_selector).val(first.url);
	        dest_selector = null; // reset
	    });
	    function esc_selector( selector ) {
	    	return selector.replace( /(:|\.|\[|\]|,)/g, "\\$1" );
	    }
	    $('.my_meta_control').on('click', 'button', function(e){
	    	e.preventDefault();
	    	dest_selector = esc_selector($(this).data('dest-selector')); // set
			media_window.open();
	    });
	});
</script>
```

**Comment by astewes** [comment]
Your updated implementation works exactly as it should - thanks!

Question: could you link me to an example of outputting repeating field meta values in a template file? I've searched your site high and low and can't seem to find any...

**Comment by farinspace** [comment]
http://www.farinspace.com/wpalchemy-metabox/#template
