### ISSUE TITLE
Invalid argument supplied for foreach() ..../MetaBox.php on line 530

### ISSUE THREAD

**Issue by hamdan-mahran** [farinspace/wpalchemy#105]
Hi,

Thank you so much for this awesome plugin, it save more time for me :)
I just have 1 issue when i using this plugin https://github.com/FrankM1/radium-one-click-demo-install to import the xml demo by one click.

It show this error:
<pre>
Warning: Invalid argument supplied for foreach() in D:\xampp\htdocs\site\wp-content\themes\sting\theme-admin\metaboxes\wpalchemy\MetaBox.php on line 530
</pre>

This issue not affect any thing, but i want to hide it.

Thanks!

**Comment by farinspace** [comment]
Can you confirm what version of wpalchemy is being used with your active theme?

**Comment by hamdan-mahran** [comment]
Hi @farinspace 
Thank you so much for reply to my issue :)
The version is: 1.5.2

But now i add code before line 530 as the following:
<pre>
if (is_array($wp_import->posts) || is_object($wp_import->posts)){
	foreach ( $wp_import->posts as $post ){
                 The other code goes here .......
	}
}
</pre>

When i add the previous condition ( if (is_array($wp_import->posts) || is_object($wp_import->posts)) )
The issue is fixed, do i'm right?

Thanks again!

**Comment by farinspace** [comment]
that sounds fine.

perhaps:

    if ( isset( $wp_import->posts ) && ( is_array( $wp_import->posts ) || is_object( $wp_import->posts ) ) )

**Comment by hamdan-mahran** [comment]
I used your code! :)
Thanks you so much @farinspace
