### ISSUE TITLE
Ho to get a simple values for the array?

### ISSUE THREAD

**Issue by hamdan-mahran** [farinspace/wpalchemy#113]
Hi,

Thank you so much for this awesome plugin!

I have issue with how to get the meta values with the simple way that i always get before.

**It gives me the following array:**
<pre>
[ucan_metas] => Array(
            [0] => a:35:{s:15:"active_meta_tab";a:1:{i:0;s:18:"ucan_custom_jquery";}s:22:"post_format_video_type";s:5:"embed"}
)
</pre>

**But i need it to be as the following:**
<pre>
Array ( [active_meta_tab] => 1 [post_format_video_type] => "embed" ) 
</pre>

**Here is my code:**
<pre>
global $post;
	global $ucan_custom_metabox_post;
	
	$ucan_get_meta  = get_post_meta(get_the_ID(), $ucan_custom_metabox_post->$post->ID, true);
	$ucan_get_field = isset($ucan_get_meta['custom_jquery_code']) ? $ucan_get_meta['custom_jquery_code'] : '';
	
	print_r($ucan_get_meta);
</pre>

Also i was using "get_the_ID()" instead of "$post->ID" but it gives me white site page!

All the best, Hamdan

**Comment by farinspace** [comment]
Make sure to have a look at the documentation (even though it is dated), it still applies: http://www.farinspace.com/wpalchemy-metabox/

It looks like the following is the issue: `$ucan_custom_metabox_post->$post->ID` try `$ucan_custom_metabox_post->get_the_id()`

**Comment by hamdan-mahran** [comment]
Hi mr farinspace,

Thank you sooooo much for the fast reply!
I appreciate that :)

When i use "get_the_id()" all site broken and give me white page without any details or errors.

Also i need to can get the array like this:
<pre>
Array ( [active_meta_tab] => 1 [post_format_video_type] => "embed" ) 
</pre>

Thanks again

**Comment by hamdan-mahran** [comment]
Also i use the documentation here more times, and i make all the steps :(
http://www.farinspace.com/wpalchemy-metabox/

I use your awesome plugin for all my themes here https://themeforest.net/user/idealtheme/portfolio

**Comment by farinspace** [comment]
What might help troubleshoot this is enabling debug .. adding `define( 'WP_DEBUG', true );` to your `wp-config.php` file, see https://codex.wordpress.org/Debugging_in_WordPress

Additionally you should confirm that `$ucan_custom_metabox_post` is indeed a WPAlchemy object.

Also instead of using `$ucan_custom_metabox_post->get_the_id()` you can use the ID/name of the meta box.

    new WPAlchemy_MetaBox(array
    (
        'id' => '_custom_meta',
        'title' => 'My Custom Meta',
        ...
    ));

    // something like the following
    get_post_meta(get_the_ID(), '_custom_meta', true);

You could also confirm this name, by having a peek in the database `wp_postmeta` table

**Comment by farinspace** [comment]
Troubleshooting is where the magic is at, additionally I often use `print_r` and `var_dump` as I develop to be sure that the data and types I expect along the way are correct.

**Comment by hamdan-mahran** [comment]
Wow !!!!
You are really awesome!

This fix the issue:
<pre>
get_post_meta(get_the_ID(), '_custom_meta', true);
</pre>

All the best to you mr farinspace :)

**Comment by hamdan-mahran** [comment]
Thank you so much :1st_place_medal:
