### ISSUE TITLE
Warning: count(): Parameter must be an array...

### ISSUE THREAD

**Issue by mauro** [farinspace/wpalchemy#115]
I get this warning:
Warning: count(): Parameter must be an array or an object that implements Countable in /Users/mauro/GitHub/mundana_wordpress/wp-content/plugins/wpalchemy/MetaBox.php on line 2048

This is the line causing the issue:
$cnt = count(!empty($this->meta[$n])?$this->meta[$n]:NULL);

**Comment by mauro** [comment]
Looks like changing NULL to array() solves the warning.
$cnt = count(!empty($this->meta[$n])?$this->meta[$n]:array());

**Comment by paulcedrick** [comment]
Hopefully this PR could fix this one -> https://github.com/farinspace/wpalchemy/pull/116/commits/9238fc178ebc2d4e5184856464dc9fb3562672d7

Still waiting for their reply
