### ISSUE TITLE
Can't edit serialized array

### ISSUE THREAD

**Issue by Obvio** [farinspace/wpalchemy#13]
first, thanks!

I'm inserting data into a custom field using values collected from a form (gravity forms) and then serialized like so:

	function serilaize_fields( $post_data, $form ) {

		$place_meta['web']       = $_POST['input_13'];
		$place_meta['facebook']  = $_POST['input_16'];
		$place_meta['twitter']   = $_POST['input_17'];
		
		$post_data['post_custom_fields']['place_meta'] = serialize( $place_meta );
		
		return $post_data;
	}

When viewing the post with the metabox I can actually see the collected values in the metabox fields but when editing/changing them and saving the post the values revert to the original ones that were inserted by the form.

When directly editing the custom field serialized array (the original WP UI) the new values seem to be ok.

for reference, the metabox code:

	$place_meta = new WPAlchemy_MetaBox( array( 'id' => 'place_meta', 
												'title' => 'Place Meta',
												'template' => TEMPLATEPATH.'/WPAlchemy/custom/place_meta.php',
												'view' => 'always_opened',
												'hide_screen_option' => TRUE,
												'context' => 'advanced',
												'priority' => 'high'
												) );

thanks again!

**Comment by farinspace** [comment]
clearing old issues .. please reopen if issue continues.
