### ISSUE TITLE
_global_foot() script causes bugs in IE [suggestion]

### ISSUE THREAD

**Issue by jenheilemann** [farinspace/wpalchemy#34]
While debugging a client's site, I noticed that working in IE tends to get buggy when the ondomready event isn't used. I wrapped the function in a `$(document).ready(function()` wrapped around the function and it cleared up the bugs. 

Cursory check of the main js interactions and they all still seem to work, but I'm no Javascript Guru - so if there's a good reason not to do this then please explain.

**Comment by farinspace** [comment]
clearing old issues .. please reopen if issue continues .. equally I'm assume this is about an older version of IE
