### ISSUE TITLE
problem importing data

### ISSUE THREAD

**Issue by stratboy** [farinspace/wpalchemy#50]
Hi. If I do an export > import with the wordpress admin, during import I get an error form wp that says that here (row 523):

update_post_meta($post_id, $key, maybe_unserialize(stripslashes($value)));

stripslashes gets an array instead of a string. So the meta field don't get saved/imported in db (checked the db to be sure).

By stripping stripslashes, all works fine.

**Comment by farinspace** [comment]
old .. latest version(s) has code which helps with importing issues .. please reopen if issue still exists
