### ISSUE TITLE
Placeholder Content

### ISSUE THREAD

**Issue by michaellautman** [farinspace/wpalchemy#52]
I'd like to have some default, or conditional content in a metabox.  This would be similar to an empty widget area in a  theme that tells someone to add a widget:

<?php if (!function_exists('dynamic_sidebar') || !dynamic_sidebar('Footer Area 2')) : ?>
		<div class="alert-box"><h4>Hey! You!</h4>
		You should like, so test out this dynamic sidebar. Check it out in Appearance > Widgets!</div>
		<?php endif; ?>

I don't know how to include the "if" when I echo my metabox in my theme template.  Any advice?

Thanks

**Comment by farinspace** [comment]
old .. if still having issues, please reopen
