### ISSUE TITLE
sidekick css/js warnings on wp 3.4.1 

### ISSUE THREAD

**Issue by stratboy** [farinspace/wpalchemy#53]
Hi, I have these wornings on a fresh wp 3.4.1 installation of sidekick:

Warning: filemtime() [function.filemtime]: stat failed for /accounts/[...]/wp-content/plugins/sidekick/assets/core.css in /accounts/[...]/wp-content/plugins/sidekick/sidekick.php on line 117

Warning: filemtime() [function.filemtime]: stat failed for /accounts/[...]/wp-content/plugins/sidekick/assets/core.js in /accounts/[...]/wp-content/plugins/sidekick/sidekick.php on line 121

Luca

**Comment by farinspace** [comment]
old .. if still having issues, please reopen (fyi, updated version of sidekick by wpalchemy to be released soon)
