### ISSUE TITLE
Drop Down to select metaboxes 

### ISSUE THREAD

**Issue by sammedve** [farinspace/wpalchemy#55]
Hi, 

I was wondering if there is an easy way to create a "mother" metabox, with a drop down of all metaboxes coded, and when one is selected, it load the appropriate metabox and insert it in the page. Something similar to a repeater but that let you choose what kind of metabox you want to add. 

Thanks in advance for your help

**Comment by farinspace** [comment]
cleaning old issues .. if this is still an issue please reopen. In regards to the issue, wpalchemy metabox doesn't keep track of which meta boxes are created
