### ISSUE TITLE
Issue with importing CSV

### ISSUE THREAD

**Issue by itsabhik** [farinspace/wpalchemy#67]
I don't know if this is the best place to ask, but I asked this question on your forum, but somehow it didn't displayed.

I imported a bunch of custom posts into my new WordPress installation and everything was successful excluding the post meta fields.

I investigated and noticed that the theme I am using is using WPAlchemy to add meta boxes.

Is there any way I can assign the CSV values to the the WPAlchemey meta boxes? Sorry, I am no PHP expert.

Regards

**Comment by farinspace** [comment]
old .. if still having issues, please reopen
