### ISSUE TITLE
PHP Errors

### ISSUE THREAD

**Issue by hguiney** [farinspace/wpalchemy#73]
I put WP in debug mode and now this is being printed out on all of the admin pages at the top:

> Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method WPAlchemy_MetaBox::_global_head() should not be called statically in wp-includes/plugin.php on line 406
> 
> Strict Standards: Non-static method WPAlchemy_MetaBox::_is_post() should not be called statically in wp-content/wpalchemy/MetaBox.php on line 1352
> 
> Strict Standards: Non-static method WPAlchemy_MetaBox::_is_post_or_page() should not be called statically in wp-content/wpalchemy/MetaBox.php on line 986
> 
> Strict Standards: Non-static method WPAlchemy_MetaBox::_get_current_post_type() should not be called statically in wp-content/wpalchemy/MetaBox.php on line 1024
> 
> Strict Standards: Non-static method WPAlchemy_MetaBox::_get_post_id() should not be called statically in wp-content/wpalchemy/MetaBox.php on line 1061

…and bottom:

> Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method WPAlchemy_MetaBox::_global_foot() should not be called statically in /srv/www/sueguiney/private/wp-includes/plugin.php on line 406
> 
> Strict Standards: Non-static method WPAlchemy_MetaBox::_is_post() should not be called statically in /srv/www/sueguiney/private/wp-content/wpalchemy/MetaBox.php on line 1516
> 
> Strict Standards: Non-static method WPAlchemy_MetaBox::_is_post_or_page() should not be called statically in /srv/www/sueguiney/private/wp-content/wpalchemy/MetaBox.php on line 986
> 
> Strict Standards: Non-static method WPAlchemy_MetaBox::_get_current_post_type() should not be called statically in /srv/www/sueguiney/private/wp-content/wpalchemy/MetaBox.php on line 1024
> 
> Strict Standards: Non-static method WPAlchemy_MetaBox::_get_post_id() should not be called statically in /srv/www/sueguiney/private/wp-content/wpalchemy/MetaBox.php on line 1061

**Comment by farinspace** [comment]
old .. resolved in recent versions .. if still having issues, please reopen
