### ISSUE TITLE
Add online phpDoc documentation

### ISSUE THREAD

**Issue by aendrew** [farinspace/wpalchemy#74]
First off — this is the second time I've used your class and I like it more and more each time. Seriously good work.

Secondly — the farinspace website is really the sole source of documentation about your class. There's the [massive monolithic data dump](http://www.farinspace.com/wpalchemy-metabox/), [the data storage post](http://www.farinspace.com/wpalchemy-metabox-data-storage-modes/), [the post on filtering and repeating](http://www.farinspace.com/wpalchemy-metabox-filtering-and-repeating-fields/) and the [install and setup post](http://www.farinspace.com/wpalchemy-metabox-install-and-setup/), in addition to any I may have missed. This is great if you're wanting a high-level overview, less great if you're wanting fast and to-the-point info on what anything does.

An example: try and find some documentation for what exactly the the_checkbox_state() method does. I'm still not entirely clear on what it does, and short of running it through a debugger (Which I think I ended up having to do the first time I used WP_Alchemy), there's no real way of figuring that out. 

(Again, that's unless I'm just web illiterate/blind and am just missing where you've documented that method — apologies if so!)

My suggestions:

1. Start using GitHub's wiki for in-depth functional documentation.
2. Continue using farinspace.com as a high-level overview and example site.
3. You already have *great* comments in your source. To go back to my example, [this line in MetaBox.php](https://github.com/farinspace/wpalchemy/blob/master/wp-content/wpalchemy/MetaBox.php#L1895) tells me *exactly* what the_checkbox_state() does. All you really need to do is convert them to Doxygen format (They're not far off) and run them through the Doxygen converter.

Let me know if you want any help with this, would love to contribute any way I can.

Thanks!

**Comment by farinspace** [comment]
going through all the issues .. marking most as old/closed, I will likely leave current code on a 1.x branch and only do updates/fixes .. perhaps starting a 2.x branch with best practices
