### ISSUE TITLE
Improve PHP version compatibility in line with WordPress minimum requirements

### ISSUE THREAD

**Issue by aendrew** [farinspace/wpalchemy#76]
As mentioned in https://github.com/farinspace/wpalchemy/issues/74, the codebase is backwards compatible to PHP4, even though [the minimum version currently required for WordPress is 5.2.4](http://wordpress.org/about/requirements/). Upgrading the codebase in favour of the more modern syntax makes WPAlchemy less likely to throw depreciated notices in future versions of PHP, in addition to improving documentation engine output. It would also have the added benefit of properly scoping the methods and attributes as intended by the phpDoc comments.

Given that the the WPAlchemy_MetaBox class' phpDoc comments already contain scope attributes, this would be little more difficult than changing the scoping keywords in the classes and ensuring the examples still run without errors.

**Comment by farinspace** [comment]
going through all the issues .. marking most as old/closed, I will likely leave current code on a 1.x branch and only do updates/fixes .. perhaps starting a 2.x branch with best practices
