### ISSUE TITLE
Strict Standards: Non-static

### ISSUE THREAD

**Issue by pbearne** [farinspace/wpalchemy#80]
I got some warnings

Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method WPAlchemy_MetaBox::_global_head() should not be called statically in /usr/local/nginx/public_html/metro_secondary_qa/wp-includes/plugin.php on line 429

Strict Standards: Non-static method WPAlchemy_MetaBox::_is_post() should not be called statically in wp-content/wpalchemy/MetaBox.php on line 1352

Strict Standards: Non-static method WPAlchemy_MetaBox::_is_post_or_page() should not be called statically in 
wp-content/wpalchemy/MetaBox.php on line 986

Strict Standards: Non-static method WPAlchemy_MetaBox::_get_current_post_type() should not be called statically in
wp-content/wpalchemy/MetaBox.php on line 1024

Strict Standards: Non-static method WPAlchemy_MetaBox::_is_page() should not be called statically in
wp-content/wpalchemy/MetaBox.php on line 1352

Strict Standards: Non-static method WPAlchemy_MetaBox::_is_post_or_page() should not be called statically in 
wp-content/wpalchemy/MetaBox.php on line 1005

Strict Standards: Non-static method WPAlchemy_MetaBox::_get_current_post_type() should not be called statically in 
wp-content/wpalchemy/MetaBox.php on line 1024

**Comment by farinspace** [comment]
old .. resolved in recent versions .. if still having issues, please reopen
