### ISSUE TITLE
I have problem with table and Repeating Fields Group

### ISSUE THREAD

**Issue by picasso2000** [farinspace/wpalchemy#83]
When insert group fields in table (fields separated by <td></td>), button for add new group fields not working, and show empty fields.
Please check this.

Without table, fields group working ok.

Code:

<table>
<? php while($mb->have_fields_and_multi('docs')): ? >
< tr ><?php $mb->the_group_open(); ? >
 
   < td > <?php $mb->the_field('price'); ?>
    < input class="small-text" type="text" name="< ?php $mb->the_name(); ? >" value="< ?php $mb->the_value(); ?>"/>< /td >
     
   < td > < ?php $mb->the_field('description'); ? >
    < textarea name="<?php $mb->the_name(); ?>" cols="50" class="regular-text"><? php $mb->the_value(); ? ></textarea >< /td >

     < td >    <a href="#" class="dodelete button">Remove Document</a>< /td >
 
< ? php $mb->the_group_close(); ? >
< /tr >
<? php endwhile; ? >
     < /table >
    
< p style="margin-bottom:15px; padding-top:5px;">< a href="#" class="docopy-docs button">add</a >< /p>

**Comment by farinspace** [comment]
closing #62 in-review
