### ISSUE TITLE
Repeat Field Not Working

### ISSUE THREAD

**Issue by aliciacatalina** [farinspace/wpalchemy#85]
I am deploying my Wordpress site to a Google App Engine, and the repeat field stopped working.
I have this on my meta-page.php
<?php global $wpalchemy_media_access; ?>
<div class="my_meta_control">
   <div style="border:1px solid #CCC; padding:10px; margin-top:10px;">
	<?php while($mb->have_fields_and_multi('docs')): ?>
	<?php $mb->the_group_open(); ?>
		<p>
			<?php $mb->the_field('datos'); ?>
			<label>Enlace de destino</label>
			<input type="text" name="<?php $mb->the_name(); ?>" value="<?php $mb->the_value(); ?>"/>
			<?php $mb->the_field('url'); ?>
			<?php $wpalchemy_media_access->setGroupName('media-n1'.$mb->get_the_index())->setInsertButtonLabel('Insertar')->setTab('type'); ?>
			<label>Archivo o Url</label>
			<?php echo $wpalchemy_media_access->getField(array('name'=>$mb->get_the_name(),'value'=>$mb->get_the_value(),'readonly'=>'readonly')); ?>
			<?php echo $wpalchemy_media_access->getButton(array('label'=>'Adjuntar un archivo')); ?>
			<br><br>
            <a href="#" class="dodelete button">Eliminar campos</a>
        </p>
	<?php $mb->the_group_close(); ?>
	<?php endwhile; ?>
</div>
    <p style="margin-bottom:15px; padding-top:5px;"><a href="#" class="docopy-docs button">Add More</a></p>
	
    </div>

And my button to Add More doesn't do anything, but the one to delete works perfectly.
Could you help me?

**Comment by sueannev** [comment]
I had a similar problem and tracked it to a line in MetaBox.php that uses jQuery's :first selector.

$('[class*=docopy-]').click(function(e)
{
	...
	var the_group = $('.wpa_group-'+ the_name +':first.tocopy', p);
	...
}

I changed the line to use jQuery filter instead as follows:
var the_group = $('.wpa_group-'+ the_name +'.tocopy', p).filter(':first');

Disco!

**Comment by farinspace** [comment]
cleaning old issues .. if this is still an issue please reopen
