### ISSUE TITLE
feature request: textual documentation for installation

### ISSUE THREAD

**Issue by sunilw** [farinspace/wpalchemy#91]
It'd be great to have written documentation for installation.

The video is ok, but it's not as clear as it could be. 
Video tutorials generally serve well as compliments to written documentation. But I don't think that they should ever be a primary source of documentation.

Thanks.

**Comment by farinspace** [comment]
agreed, will keep this in mind for a future version .. for now the primary source of documentation can be found here: http://www.farinspace.com/wpalchemy-metabox/
