### ISSUE TITLE
Multiple orderby in WP_Query

### ISSUE THREAD

**Issue by BrianSahagun** [farinspace/wpalchemy#92]
Good day, may I ask how can we have more than one criteria for sorting posts based on meta_key?

My arguments in WP_Query:
'meta_key'      => $destination_info_meta->get_the_name('date'),
'orderby'       => 'meta_value',

**Comment by farinspace** [comment]
clearing old issues .. if issue persists please reopen

For reference: https://codex.wordpress.org/Class_Reference/WP_Query#Order_.26_Orderby_Parameters
